---
name: CI
on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version-file: '.python-version'

      - uses: actions/cache@v4
        id: cache-dependencies
        with:
          path: |
            .venv
          key: ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/*requirements.txt') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          pip install uv
          uv venv
          source .venv/bin/activate
          make install-dev-deps

      - name: Set up environment vars
        run: |
          cp env.example src/.env

      - name: Run the linter
        run: |
          source .venv/bin/activate
          make lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      rabbitmq:
        image: rabbitmq:3.12.14-management-alpine
        ports:
          - 5672:5672

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version-file: '.python-version'

      - name: Set up environment vars
        run: |
          cp env.example src/.env

      - uses: actions/cache/restore@v4
        id: cache-dependencies
        with:
          path: |
            .venv
          key: ${{ runner.os }}-venv-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/*requirements.txt') }}

      - name: Run the tests
        run: |
          source .venv/bin/activate
          make test
